---

- hosts: brooklyn_server
  remote_user: root
  tasks:

    # -------------------------------------------------------------------------
    # Freshen up the host
    # -------------------------------------------------------------------------

    - name: Disable dpkg fsync
      raw: test -e /etc/dpkg/dpkg.cfg.d/unsafe-io || echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Upgrade debian
      apt:
        update_cache: true
        upgrade: true

    # -------------------------------------------------------------------------
    # Install shit that should be there and fix locales
    # -------------------------------------------------------------------------

    - name: Install setup tools
      apt:
        name: "{{ item }}"
        allow_unauthenticated: yes
      with_items:
        - openjdk-8-jre
        - nginx

    - name: Delete nginx default file
      file:
        path: /etc/nginx/sites-available/default
        state: absent

    - name: Delete nginx default file link
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: copy nginx conf
      copy:
        src: brooklyn.conf
        dest: /etc/nginx/sites-enabled/brooklyn.conf
        follow: yes

    - name: copy nginx conf
      copy:
        src: brooklyn.conf
        dest: /etc/nginx/sites-available/brooklyn.conf
        follow: yes

    - name: Restart nginx
      service:
        name: nginx
        state: restarted

    - name: Download apache-brooklyn-1.0.0.deb
      command: "wget --no-check-certificate https://ipfs.subutai.io/ipfs/QmQNxEgKEPssNiA2VGn7ScZKrKAxgr6ptcF4oefCskcrVm/apache-brooklyn-1.0.0.deb"

    - name: Install apache-brooklyn-1.0.0.deb
      apt:
        deb: /root/apache-brooklyn-1.0.0.deb

    - name: Restart brooklyn
      service:
        name: brooklyn
        state: restarted

    - name: Remove apache-brooklyn-1.0.0.deb
      file:
       path: /root/apache-brooklyn-1.0.0.deb
       state: absent
